# Generated by Django 3.2.16 on 2024-06-27 00:26

from django.db import migrations
from datetime import datetime

def populate_tasks(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Label = apps.get_model('tasks', 'Label')

    label1 = Label.objects.create(name='Personal')
    label2 = Label.objects.create(name='Work')
    label3 = Label.objects.create(name='Bug')
    label4 = Label.objects.create(name='Improvement')
    label5 = Label.objects.create(name='Needs Review')
    label6 = Label.objects.create(name='Tech Debt')
    label7 = Label.objects.create(name='Hotfix')

    task1 = Task.objects.create(
        title='Task 1',
        description='Description for Task 1',
        status='to-do',
        priority='medium',
        created_at=datetime.now(),
        updated_at=datetime.now()
    )
    task1.labels.add(label1)
    task1.labels.add(label3)
    task1.labels.add(label4)

    task2 = Task.objects.create(
        title='Task 2',
        description='Description for Task 2',
        status='in_progress',
        priority='high',
        created_at=datetime.now(),
        updated_at=datetime.now()
    )
    task2.labels.add(label2)
    task2.labels.add(label3)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(populate_tasks),
    ]
