# Generated by Django 3.2.16 on 2024-06-27 00:22

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser(username='admin', email='admin@example.com', password='admin')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
