# Generated by Django 3.2.16 on 2024-06-27 00:22

from django.db import migrations
from django.contrib.auth.models import User

def create_user(apps, schema_editor):
    User.objects.create_user(username='user', email='user@example.com', password='user')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
