FROM python:3.9.16-slim-bullseye

RUN apt update && apt install -y \
    bash \
    postgresql-server-dev-all \
    python3-dev \
    git \
    libcurl4-openssl-dev \
    libssl-dev \
    libgnutls28-dev \
    libjpeg-dev \
    libffi-dev \
    gcc \
    g++ \
    libxslt-dev \
    nano \
    procps \
    htop \
    build-essential \
    curl

RUN apt-get install libjemalloc2 && rm -rf /var/lib/apt/lists/*
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libjemalloc.so.2

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV PYTHONPATH "${PYTHONPATH}:/app"

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip

ADD ./requirements/* /app/requirements/
RUN pip install "setuptools==58.0.0"
RUN pip install --no-cache-dir -r /app/requirements/common.txt